version: '3'
services:
  flyway:
    image: flyway/flyway:9.7.0
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:./migrations migrate
    volumes:
      - /migrations:/migrations
      - /flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - TRANSACTIONS_FLYWAY_URL=${TRANSACTIONS_FLYWAY_URL}
    - TRANSACTIONS_SCHEMA_NAME=${POSTGRES_DB}
    networks:
      - postgres-compose-network
networks: 
  postgres-compose-network:
    driver: bridge