version: '3.5'

services:

  clients-database:
    container_name: clients-database
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - transactions-network
    restart: unless-stopped
  
  clients-flyway:
    container_name: clients-flyway
    image: flyway/flyway:9.7.0
    environment:
      - FLYWAY_EDITION=community
    command: -url=jdbc:postgresql://clients-database:5433/${POSTGRES_DB} -schemas=${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=50 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - clients-database
    networks:
      - transactions-network

networks:
  transactions-network:
    driver: bridge