version: '3.5'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    # volumes:
    #    - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  flyway:
    image: flyway/flyway:9.7.0
    environment:
      - FLYWAY_EDITION=community
    command: -url=jdbc:postgresql://postgres:5432/postgres -schemas=${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=50 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

# volumes:
#     postgres: